### ISSUE TITLE
classify.py 

### ISSUE THREAD

**Issue by HaifeiOuyang** [Junsong-Wang/deep-learning#1]
使用修改后的classify.py，测试mnist模型。测试图片为单通道的28*28
error:
Traceback (most recent call last):
  File "python/classifymnist.py", line 178, in <module>
    main(sys.argv)
  File "python/classifymnist.py", line 134, in main
    channel_swap=channel_swap)
  File "/home/ouy/Downloads/caffe/python/caffe/classifier.py", line 40, in __init__
    self.transformer.set_channel_swap(in_, channel_swap)
  File "/home/ouy/Downloads/caffe/python/caffe/io.py", line 217, in set_channel_swap
    raise Exception('Channel swap needs to have the same number of '
Exception: Channel swap needs to have the same number of dimensions as the input channels.

**Comment by HaifeiOuyang** [comment]
修改后的classify.py代码：
`#!/usr/bin/env python
"""
classify.py is an out-of-the-box image classifer callable from the command line.

By default it configures and runs the Caffe reference ImageNet model.
"""
import numpy as np
import os
import sys
import argparse
import glob
import time
import pandas as pa # load data analysis package

import caffe


def main(argv):
    pycaffe_dir = os.path.dirname(__file__)

    parser = argparse.ArgumentParser()
    # Required arguments: input and output files.
    parser.add_argument(
        "input_file",
        help="Input image, directory, or npy."
    )
    parser.add_argument(
        "output_file",
        help="Output npy filename."
    )
    # Optional arguments.
    parser.add_argument(
        "--model_def",
        default=os.path.join(pycaffe_dir,
                "../examples/mnist/lenet.prototxt"), #deploy.prototxt
        help="Model definition file."
    )
    parser.add_argument(
        "--pretrained_model",
        default=os.path.join(pycaffe_dir,
                "../examples/mnist/lenet_iter_10000.caffemodel"),# mnist_caffemodel
        help="Trained model weights file."
    )

############## new add
    parser.add_argument(
        "--labels_file",
        default=os.path.join(pycaffe_dir,
               "../examples/mnist/synset_words.txt"), # output file of labels
        help="mnist result words file"
    )

    parser.add_argument(
        "--force_grayscale",
        action='store_true', 
        help="Converts RGB images down to single-channel grayscale versions,"+
                   "useful for single-channel networks like MNIST."
    )

    parser.add_argument(
        "--print_results",
        action='store_true', 
        help="Write output text to stdout rather than serializing to a file."																																																																																																																																																									
    )
############## new add

    parser.add_argument(
        "--gpu",
        action='store_true',
        help="Switch for gpu computation."
    )
    parser.add_argument(
        "--center_only",
        action='store_true',
        help="Switch for prediction from center crop alone instead of " +
             "averaging predictions across crops (default)."
    )
    parser.add_argument(
        "--images_dim",
        default='28,28',
        help="Canonical 'height,width' dimensions of input images."
    )
    parser.add_argument(
        "--mean_file",
        default=os.path.join(pycaffe_dir,
                             '../examples/mnist/mean.npy'),
        help="Data set image mean of [Channels x Height x Width] dimensions " +
             "(numpy array). Set to '' for no mean subtraction."
    )
    parser.add_argument(
        "--input_scale",
        type=float,
        help="Multiply input features by this scale to finish preprocessing."
    )
    parser.add_argument(
        "--raw_scale",
        type=float,
        default=255.0,
        help="Multiply raw input by this scale before preprocessing."
    )
    parser.add_argument(
        "--channel_swap",
        default='2,1,0',
        help="Order to permute input channels. The default converts " +
             "RGB -> BGR since BGR is the Caffe default by way of OpenCV."
    )
    parser.add_argument(
        "--ext",
        default='jpg',
        help="Image file extension to take as input when a directory " +
             "is given as the input file."
    )
    args = parser.parse_args()

    image_dims = [int(s) for s in args.images_dim.split(',')]

    mean, channel_swap = None, None
    if args.mean_file:
        mean = np.load(args.mean_file).mean(1).mean(1)
    if args.channel_swap:
        channel_swap = [int(s) for s in args.channel_swap.split(',')]

    if args.gpu:
        caffe.set_mode_gpu()
        print("GPU mode")
    else:
        caffe.set_mode_cpu()
        print("CPU mode")

    # Make classifier.
    classifier = caffe.Classifier(args.model_def, args.pretrained_model,
            image_dims=image_dims, mean=mean,
            input_scale=args.input_scale, raw_scale=args.raw_scale,
            channel_swap=channel_swap)

    # Load numpy array (.npy), directory glob (*.jpg), or image file.
    args.input_file = os.path.expanduser(args.input_file)
    if args.input_file.endswith('npy'):
        print("Loading file: %s" % args.input_file)
        inputs = np.load(args.input_file)
    elif os.path.isdir(args.input_file):
        print("Loading folder: %s" % args.input_file)
        inputs =[caffe.io.load_image(im_f)
                 for im_f in glob.glob(args.input_file + '/*.' + args.ext)]
    else:
        print("Loading file: %s" % args.input_file)
        inputs = [caffe.io.load_image(args.input_file)]

    print("Classifying %d inputs." % len(inputs))

    # Classify.
    start = time.time()
    predictions = classifier.predict(inputs, not args.center_only)
    print("Done in %.2f s." % (time.time() - start))

###### add output result to print
    if args.print_results:
       with open(args.labels_file) as f:
           labels_df=pd.DataFrame([{'synset_id':l.strip().split(' ')[0], 'name': ' '.join(l.strip().split(' ')[1:]).split(',')[0]} for l in f.readlines()])
           labels = labels.df.sort('synset_id')['name'].values


           indices = (-scores).argsort()[:5]
           predictions = labels[indices]
           print predictions
           print scores

           meta = [(p, '%.5f' % scores[i]) for i,p in zip(indices, predictions)]
           print meta
###### add output result to print

    # Save
    print("Saving results into %s" % args.output_file)
    np.save(args.output_file, predictions)


if __name__ == '__main__':
    main(sys.argv)
`

**Comment by HaifeiOuyang** [comment]
开始用的三通道图片进行测试，报错后改为单通道的，然后还是报错，因为里面的代码也不是很熟，不知道哪里错了。求指导！

**Comment by Junsong-Wang** [comment]
This example is designed for Imagenet. the input of MINIST model is single channel, not RGB, and you should use a gray image. The major problem is channel swap, which can not be applied, and you can by pass it by set it to None manually, like
--------------------------------------------- -------------------------------------------------------------------
parser.add_argument(
    "--channel_swap",
    default=None,
    help="Order to permute input channels. The default converts " +
         "RGB -> BGR since BGR is the Caffe default by way of OpenCV."
)
------------------------------------------------------------------------------------------------------------------

**Comment by Junsong-Wang** [comment]
This is a good link for you to follow... 

http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/01-learning-lenet.ipynb

**Comment by HaifeiOuyang** [comment]
谢谢，错误找到了，加上您的代码，还有io.py文件中
`def load_image(filename, color=True)`
将True改为False，问题得以解决！
